--1 find total customers by countries. 
	SELECT 
		country,
		COUNT(customer_key) AS Total_Customers
	FROM gold.dim_customers
	GROUP BY country
	ORDER BY Total_Customers DESC

--2 find total customers by gender.
	SELECT 
		gender,
		COUNT(customer_key) AS total_customer_gender
	FROM gold.dim_customers
	GROUP BY gender
	ORDER BY total_customer_gender DESC

--3 find total products by category. 
	SELECT 
		category,
		COUNT(product_key) AS total_product
	FROM gold.dim_products
	GROUP BY category
	ORDER BY total_product DESC

--4 what is the average cost in each category?
	SELECT 
		category,
		AVG(cost) AS avg_cost
	FROM gold.dim_products 
	GROUP BY category
	ORDER BY avg_cost DESC

--5 what is the total revenue generated for each category? 
	SELECT TOP 10 * 
	FROM gold.dim_products;

	SELECT 
		dp.category,
		SUM(fs.sales_amount) AS total_revenue
	FROM gold.fact_sales as fs
	LEFT JOIN gold.dim_products  as dp
	ON dp.product_key = fs.product_key
	GROUP BY dp.category
	ORDER BY total_revenue DESC
	
--6 find total revenue is generated by each customers.
	SELECT 
		c.customer_key,
		c.first_name,
		c.last_name,
		SUM(f.sales_amount) AS total_revenue
	FROM gold.fact_sales as f
	LEFT JOIN gold.dim_customers AS c
	ON f.customer_key = c.customer_key
	GROUP BY 
		c.customer_key,
		c.first_name,
		c.last_name
	ORDER BY total_revenue DESC

--7 What is the distribution of sold items across countries?
SELECT 
c.country,
SUM(f.quantity) AS total_sales
FROM gold.fact_sales as f 
LEFT JOIN gold.dim_customers as c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sales DESC


